// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	order/order.proto

It has these top-level messages:
	OrderRequest
	OrderResponse
*/
package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderRequest struct {
	ItemId       int32  `protobuf:"varint,1,opt,name=itemId" json:"itemId,omitempty"`
	ItemName     string `protobuf:"bytes,2,opt,name=itemName" json:"itemName,omitempty"`
	ItemQuantity int32  `protobuf:"varint,3,opt,name=itemQuantity" json:"itemQuantity,omitempty"`
}

func (m *OrderRequest) Reset()                    { *m = OrderRequest{} }
func (m *OrderRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()               {}
func (*OrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OrderRequest) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *OrderRequest) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *OrderRequest) GetItemQuantity() int32 {
	if m != nil {
		return m.ItemQuantity
	}
	return 0
}

type OrderResponse struct {
	OrderPlaced bool `protobuf:"varint,1,opt,name=orderPlaced" json:"orderPlaced,omitempty"`
}

func (m *OrderResponse) Reset()                    { *m = OrderResponse{} }
func (m *OrderResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()               {}
func (*OrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OrderResponse) GetOrderPlaced() bool {
	if m != nil {
		return m.OrderPlaced
	}
	return false
}

func init() {
	proto.RegisterType((*OrderRequest)(nil), "order.OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "order.OrderResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OrderService service

type OrderServiceClient interface {
	PlaceOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) PlaceOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := grpc.Invoke(ctx, "/order.OrderService/PlaceOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceServer interface {
	PlaceOrder(context.Context, *OrderRequest) (*OrderResponse, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/PlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PlaceOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _OrderService_PlaceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/order.proto",
}

func init() { proto.RegisterFile("order/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x2f, 0x4a, 0x49,
	0x2d, 0xd2, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x52, 0x1a,
	0x17, 0x8f, 0x3f, 0x88, 0x11, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc6, 0xc5, 0x96,
	0x59, 0x92, 0x9a, 0xeb, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x09, 0x49,
	0x71, 0x71, 0x80, 0x58, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70,
	0xbe, 0x90, 0x12, 0x17, 0x0f, 0x88, 0x1d, 0x58, 0x9a, 0x98, 0x57, 0x92, 0x59, 0x52, 0x29, 0xc1,
	0x0c, 0xd6, 0x89, 0x22, 0xa6, 0x64, 0xc8, 0xc5, 0x0b, 0xb5, 0xa7, 0xb8, 0x20, 0x3f, 0xaf, 0x38,
	0x55, 0x48, 0x81, 0x8b, 0x1b, 0xec, 0x82, 0x80, 0x9c, 0xc4, 0xe4, 0x54, 0x88, 0x6d, 0x1c, 0x41,
	0xc8, 0x42, 0x46, 0x9e, 0x50, 0xa7, 0x05, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x59, 0x72,
	0x71, 0x81, 0x65, 0xc0, 0x82, 0x42, 0xc2, 0x7a, 0x10, 0xdf, 0x20, 0xbb, 0x5e, 0x4a, 0x04, 0x55,
	0x10, 0x62, 0x95, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0xcf, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xec, 0xf9, 0x53, 0xbc, 0x08, 0x01, 0x00, 0x00,
}
